pipeline {

 agent any

 parameters {

  choice(
   name: 'ENV',
   choices: ['dev','staging'],
   description: 'Select Environment'
  )

  choice(
   name: 'TEST_TYPE',
   choices: ['smoke','regression','e2e'],
   description: 'Select Test Suite'
  )

 }

 stages {

  stage('Checkout') {

   steps {

    git url: 'https://github.com/boriratkk-boop/playwright-labs.git'

   }

  }

  stage('Install Dependencies') {

   steps {

    dir('automation') {

     sh 'npm install'
     sh 'npx playwright install'

    }

   }

  }

  stage('Run Tests') {

   steps {

    dir('automation') {

     sh """
     export TEST_ENV=${params.ENV}
     npm run ${params.TEST_TYPE}
     """

    }

   }

  }

  stage('Generate Allure Report') {

   steps {

    dir('automation') {

     sh 'allure generate allure-results --clean -o allure-report'

    }

   }

  }

 }

}