pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('automation') {
                    bat 'npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('automation') {
                    bat 'npx playwright test'
                }
            }
        }

        stage('Playwright Report') {
    steps {
        publishHTML([
            reportDir: 'automation/playwright-report',
            reportFiles: 'index.html',
            reportName: 'Playwright Report'
            ])
        }
    }

    }
}